export INFO_DISPLAY_DEBUG=1
export INFO_DISPLAY_LOG_LEVEL=DEBUG  # {DEBUG,INFO,WARN,ERROR,FATAL}
export INFO_DISPLAY_DB=data/db.sqlite3
export INFO_DISPLAY_SPACE_API_URL=http://localhost:8081/api/room
